AllCops:
  Exclude:
    - 'db/schema.rb'
    - 'db/migrate/*.rb'
    - 'node_modules/**/*'
    - 'bin/*'
    - 'config/initializers/simple_form_bootstrap.rb'
    - 'config/initializers/simple_form.rb'
    - 'config/application.rb'
    - 'config/environments/*'
    - 'test/dummy/bin/update'
    - 'test/dummy/bin/setup'
    - 'test/dummy/db/schema.rb'
    - 'test/dummy/db/migrate/*.rb'
    - 'test/dummy/node_modules/**/*'
    - 'test/dummy/bin/*'
    - 'test/dummy/config/initializers/simple_form_bootstrap.rb'
    - 'test/dummy/config/initializers/simple_form.rb'
    - 'test/dummy/config/application.rb'
    - 'test/dummy/config/environments/*'

Rails:
  Enabled: true

Rails/HasAndBelongsToMany:
  Enabled: false

Rails/UnknownEnv:
  Environments:
    - production
    - development
    - test
    - staging

Rails/LexicallyScopedActionFilter:
  Enabled: false

Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 100

Metrics/MethodLength:
  Max: 20

Metrics/ClassLength:
  Exclude:
    - test/**/*

Metrics/BlockLength:
  Exclude:
    - test/**/*

Bundler/OrderedGems:
  Enabled: false

Style/EmptyMethod:
  Enabled: false

Style/ClassAndModuleChildren:
  EnforcedStyle: 'nested'

Style/TrailingCommaInArrayLiteral:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
